### ISSUE TITLE
The latest update adds additional search icon when including chosen.scss

### ISSUE THREAD

**Issue by danielnolan** [tsechingho/chosen-rails#103]
When including chosen.scss the search icon gets doubled up. If I only include chosen-base.scss this does not happen. 
![screen shot 2018-03-28 at 3 51 03 pm](https://user-images.githubusercontent.com/635285/38094431-b70371e4-333b-11e8-8a32-9762af0aeebe.png)

**Comment by tsechingho** [comment]
Sorry for late response.
We have v1.9.0 to have `chosen.scss` updated.
