### ISSUE TITLE
Sass is deprecated soon

### ISSUE THREAD

**Issue by xinlangzi** [tsechingho/chosen-rails#108]
This gem has dependency sass_rails which use sass too. Ruby Sass is deprecated and will be unmaintained as of 26 March 2019. Will you update dependency to use sassc_rails? Thank you.

http://sass.logdown.com/posts/7081811

**Comment by varyonic** [comment]
sass_rails >= 6.0.x wraps sassc-rails

**Comment by varyonic** [comment]
Duplicates #95

**Comment by JulienItard** [comment]
> sass_rails >= 6.0.x wraps sassc-rails

Not anymore ! see https://github.com/rails/rails/issues/32896#issuecomment-451758771

Would be great to use sassc here now :)

**Comment by tsechingho** [comment]
Sorry for late response.
We have v1.9.0 to use sassc-rails now.
