### ISSUE TITLE
Getting 'File to import not found or unreadable: chosen.' error while upgrading my app from Rails 5 to Rails 6.

### ISSUE THREAD

**Issue by asadullah-svs** [tsechingho/chosen-rails#112]
I recently upgraded my app from rails 5 to rails 6 and everything seems to be working just fine except of the chosen-rails. Chosen rails is working fine in rails 5.

In my .scss file, i'm importing it as  @import 'chosen';

And in my app/javascript/pack/somename.js file, i'm requiring it as: require("chosen-jquery")

And of course my gemfile contain chosen-rails gem.
As I've mentioned above gem is working fine in rails 5 but giving issues in rails 6 which brings me to the question whether chosen-rails is compatible with version 6 of rails?

If you need any other information about the app for debugging i'm happy to provide it to you. Cheers!

**Comment by macfanatic** [comment]
Same issue upgrading to rails 6 here.

**Comment by shioimm** [comment]
I've got same issue, too. 
And I found that chosen-rails-1.8.7 seams to be missed in the assets.paths.
When I try to execute `Rails.application.config.assets.paths` in console, there is no paths to chosen-rails.

**Comment by asadullah-svs** [comment]
Hello guys. It turns out that chosen-rails is not compatible with rails 6, you can see it in their file 

https://github.com/tsechingho/chosen-rails/blob/master/lib/chosen-rails.rb#L9

However, you can see this pull request which fixes this issue: https://github.com/tsechingho/chosen-rails/pull/111

In short, update the chosen-rails gem in gemfile as follows and hopefully the error will be resolved:

gem 'chosen-rails', :git => "https://github.com/varyonic/chosen-rails", :branch => "rails-6"

Don't forget bundle install.

**Comment by johnmosesman** [comment]
Hey any progress on releasing this fix?

**Comment by varyonic** [comment]
I emailed the maintainer volunteering help and another Railsgirls Taiwan member with no response.

**Comment by tsechingho** [comment]
Sorry for late response.
We have v1.9.0 to support rails 6 now.
