### ISSUE TITLE
Bootstrap Chosen and SCSS

### ISSUE THREAD

**Issue by Nerian** [tsechingho/chosen-rails#19]
Hi,

I am using Bootstrap [1] in SCSS flavor and I would like to have chosen styled according to bootstrap styles. The changes were pretty straightforward and you can see it on [2]. 

Would you be OK if I make a pull request?

The developer would be able to switch to bootstrap by using `*= require chosen.bootstrap`

Thanks.

[1] https://github.com/thomas-mcdonald/bootstrap-sass
[2] https://gist.github.com/Nerian/4948345

**Comment by exadeci** [comment]
So this never got pr ?

**Comment by Nerian** [comment]
Mmm, I think I ran into some errors or something :)

I am using the scss from: https://github.com/alxlit/bootstrap-chosen and looks bootstrapy. It uses a bunch of variables to configure the stylesheet. Maybe you could merge that work onto this repo.
