### ISSUE TITLE
couldn't find file 'chosen'

### ISSUE THREAD

**Issue by lucianot** [tsechingho/chosen-rails#3]
I've added the gem and _*= require chosen_ to application.css. However, when I try to use Chosen, I get the following error:

```
couldn't find file 'chosen'
  (in /Users/.../app/assets/stylesheets/application.css:12)
```

**Comment by mattwarrenrnp** [comment]
I struggled with this for a while and was unable to find out which gem was causing problems.  Ended up just grabbing the chosen.js from https://github.com/harvesthq/chosen/releases and stuffing it in as a vendor asset.
