### ISSUE TITLE
Problem with chosen input in Bootstrap tab

### ISSUE THREAD

**Issue by uriklar** [tsechingho/chosen-rails#42]
Hi,
I have a form and i have two chosen select menus in each tab.
Sorry about all the code, but I am really clueless to what's going on here!
Here is the basic structure:
= simple_form_for(@apartment) do |f|
  %ul.nav.nav-tabs
    %li.active
      %a{href: "#apartment_info", data: {toggle: "tab"}} Apartment Info
    %li
      %a{href: "#bedroom_info", data: {toggle: "tab"}} Bedroom Info

  #form_fields
    .tab-content
      .tab-pane.active#apartment_info
        = render 'apartments/upload/apt_info', :f => f
      .tab-pane#bedroom_info
        = render 'apartments/upload/room_info', :f => f

apt_info:
f.association :equipment, label_method: :name, value_method: :id, include_blank: false, collection: EquipmentCategory.order(:name), as: :grouped_select, group_method: :equipment,input_html: { multiple: true, include_blank: false }

room_info:
= f.simple_fields_for :rooms do |ff|
    = render 'room_fields', f: ff
room_fields:
f.association :equipment, label_method: :name, value_method: :id, include_blank: false, collection: EquipmentCategory.order(:name), as: :grouped_select, group_method: :equipment,input_html: { multiple: true, include_blank: false }

I've tried many different options and they all work, in one condition:
The two chosen inputs are in the same tab. When I separate them to two separate tabs, the one on the second tab is added with: display:none, and even when i manually set the display to "block" i get a regular multi choice select and not the chosen one...

Do you have any idea as to why this is happening. Again, all of my tests with the two selects in the same tab worked just fine...

Thanks!

**Comment by tjschuck** [comment]
I think this is the same issue as https://github.com/harvesthq/chosen/issues/2332, which provides a workaround.

Try explicitly setting the width to 100%:

```javascript
$("#myselect").chosen({ width: "100%" }); 
```
