### ISSUE TITLE
couln't find file 'chosen-jquery' error during deploy.

### ISSUE THREAD

**Issue by devtoro** [tsechingho/chosen-rails#46]
Dear All, 

I am trying to deploy an app in rails 3.2.16, with capistrano on a vps. This is my first time doing that. During the deployment process, I get the following error: "couldn't find file "chosen-jquery" '. The rpoblem is that my gem versions and generally the whole environment is the same on the server and my testing machine. I get the error during the "assets:precompile" command execution.

Any suggestions?

I am using the gem chosen -v 1.0.2, rails 3.2.16 and Ruby 1.9.3.

Here is my gemfile:

---

source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'mysql2'

group :assets do
  gem 'sass-rails',   '~> 3.2.3', require: false
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'ckeditor',                                        '4.0.4'
gem 'carrierwave',                                '0.8.0'
gem 'devise',                                        '2.2.3'
gem 'globalize3',                                '0.3.0'
gem 'babosa',                                        '0.3.9'
gem 'haml',                                                '4.0.4'
gem 'friendly_id',                                '4.0.9'
gem 'simple_form',                                '2.0.4'
gem 'kaminari',                                        '0.14.0'
gem 'nokogiri',                                        '1.6.1'
gem 'jquery-fileupload-rails',        '0.4.0'
gem 'ancestry',                                        '1.3.0'
gem 'ransack',                                        '0.7.2'
gem 'simple-navigation',                '3.10.0'
gem 'mime-types',                                '~>1.21'
gem 'mini_magick',                                '3.5.0'
gem 'acts_as_list',                                '0.1.9'
gem 'chosen-rails', require: false
gem 'pry'
## gem 'passenger'

and my application.js manifest:

---

//= require jquery-1.10.2.min
//= require jquery_ujs
//= require ckeditor/init
//= require jquery.fancybox-1.3.4.pack
//= require jquery.easing-1.3.pack
//= require jquery.mousewheel-3.0.4.pack
//= require chosen-jquery
//= require scripts
//= require admin_scripts

---

Thank you in advance for your time and effort :)

**Comment by whitepaperclip** [comment]
In case anyone else ever has to deal with this: it's because the chosen-jquery gem has to be declared *above* whatever other gem depends on it.

**Comment by andrewhaines** [comment]
@whitepaperclip thanks! Your advice saved me a serious headache.
