### ISSUE TITLE
Rails 4.1 compile issue

### ISSUE THREAD

**Issue by almaron** [tsechingho/chosen-rails#55]
Strange thing, but if I just add 

```
//= require chosen.jquery
```

to my application.js it will result in a "ReferenceError: AbstractChosen is not defined". 
Seems like that line includes the chosen.jquery.coffee file, but not the correct chosen.jquery.js

When I copied the contents of chosen.jquery.js into application.js like this

```
//= require lib/abstract-chosen
//= require lib/select-parser
//= require chosen.jquery
```

that error went away.

Possible solution: rename the chosen.jquery.js or the chosen.jquery.coffee file so that the asset pipeline does not get confused.

**Comment by asiniy** [comment]
Replace `chosen.jquery` with `chosen-jquery` dude ;)
