### ISSUE TITLE
Sometime not working

### ISSUE THREAD

**Issue by maurosbu** [tsechingho/chosen-rails#60]
Version 1.1.1, sometime it doesn't work and I get standard select menu.

**Comment by addstar34** [comment]
Same issue (or slightly different?) When the page first loads it shows chosen style menu correctly. Then if I leave that page and then return to the page again it shows the standard select menu.
I think this is a turbolinks issue as I removed turbolinks and it seems to have fixed the issue.

**Comment by addstar34** [comment]
My issue was turbolinks and this has been discussed and resolved in closed issue #58. @maurosbu and @Razesdark maybe this will fix your issue as well?

**Comment by Razesdark** [comment]
Its been over a year, but yea. Disabling turbolinks fixed my issues as well.
