### ISSUE TITLE
in Raisl 4.2.0 upon install of chosen-rails, nothing gets copied to vendor/assets/

### ISSUE THREAD

**Issue by chewmanfoo** [tsechingho/chosen-rails#67]
error when running for the first time:

couldn't find file 'chosen'

**Comment by nicolas-besnard** [comment]
Nothing is copied in vour vendor/assets on your apps. Everything is on your Gemset directory

**Comment by chewmanfoo** [comment]
Yeah I'm an idiot.  Ignore me.
