### ISSUE TITLE
ExecJS::ProgramError: TypeError: Cannot set property 'root' of null

### ISSUE THREAD

**Issue by alpracka** [tsechingho/chosen-rails#69]
I'm getting this error when deploying and assets are being precompiled.

```
[bf4ff2dc] 	ExecJS::ProgramError: TypeError: Cannot set property 'root' of null
DEBUG [bf4ff2dc] 	  (in /home/user/app/shared/bundle/ruby/2.1.0/gems/chosen-rails-1.3.0/vendor/assets/javascripts/lib/select-parser.coffee)
```

```
chosen-rails 1.3.0
rails 4.2.0
sass 3.4.11
coffee-script 2.3.0
```

The `1.2.0` runs ok.

**Comment by itmammoth** [comment]
I guess that's the same problem as https://github.com/jashkenas/coffeescript/issues/3829

**Comment by cowholio4** [comment]
Confirmed that it's not chosen's problem. 

Fixed by upgrading nodejs. 

```
node --version
v0.12.2
```

**Comment by alpracka** [comment]
I've removed 'therubyracer' gem from the production group (my assets were compiling at production env) and I've installed nodejs. Problem solved.
