### ISSUE TITLE
uninitialized constant Sprockets::SassCacheStore

### ISSUE THREAD

**Issue by sadiqmmm** [tsechingho/chosen-rails#70]
Error: uninitialized constant Sprockets::SassCacheStore

compass-rails gem is not capable with sprocket 3.0 rails 4.2.

As Compass-rails is the compatibility gem for chosen rails gem

**Comment by sadiqmmm** [comment]
Please update this gem with compass-rails dependency to v2.0.4 w/ rails 4.2 support.

Thanks

**Comment by buenaventure** [comment]
+1

**Comment by Streek** [comment]
+1

**Comment by victorlcampos** [comment]
+1

**Comment by qpowell** [comment]
+1

**Comment by vanboom** [comment]
+1 upgrading to the master branch did not solve this issue

**Comment by qpowell** [comment]
I ended up just forking it, updating the dependencies in my fork, and referencing that in my gemfile with: `gem 'chosen-rails', git: 'git://github.com/qpowell/chosen-rails.git'`.

Obviously, you may not want to do this in your project depending on what other dependencies you have, but it's an option.

**Comment by woohoou** [comment]
+1

**Comment by FlavienBusseuil** [comment]
+1

**Comment by chardos** [comment]
+1

**Comment by henriquecf** [comment]
+1

**Comment by goldnuggets24** [comment]
+1

**Comment by Saworieza** [comment]
+1

**Comment by tsechingho** [comment]
The related compass-rails issue is https://github.com/Compass/compass-rails/issues/236.

As @Streek said, compass-rails master is working with sprockets 3.x.

But it's safe to use a dynamic gem dependencies for compass-rails.

Here is chosen-rails 1.4.2 to deal this issue.

Sorry for my lazy work. Thanks all of you.

**Comment by nihtalak** [comment]
+1

**Comment by famousky** [comment]
+1

**Comment by luapearth** [comment]
+1

**Comment by contradictioned** [comment]
But still compass 2.0.4 is not compatible with the current sass version:

    In snapshot (Gemfile.lock):
      sass-rails (= 5.0.3)

    In Gemfile:
      chosen-rails (~> 1.4.2) ruby depends on
        sass-rails (>= 3.2) ruby

      chosen-rails (~> 1.4.2) ruby depends on
        compass-rails (>= 2.0.4) ruby depends on
          sass-rails (<= 5.0.1) ruby

      sass-rails (~> 5.0) ruby


(not a chosen-rails problem, just wanted to report in case anybody else has this problem)

**Comment by yayayahahaha** [comment]
I use solution of @Streek , which is 

gem "compass-rails", github: "Compass/compass-rails", branch: "master"

then 

$bundle update.

and the final step is, restart the server.
and the final step is, restart the server.
and the final step is, restart the server.

it's important that I have to say three times.
thanks a lot.

**Comment by benwoodward** [comment]
@yayayahahaha ```bundle update``` is risky, as it'll update *all* your dependencies which can cause things in your application to break. Ideally one should have dependencies tied down to a version, e.g. ```~> 5.5``` to avoid this issue, but still.

```bundle install``` will recognise the change and update the respective dependencies without touching everything else.

**Comment by iurifq** [comment]
Version `2.0.5` of `compass-rails` seems to fix the issue.

**Comment by abrambailey** [comment]
I removed compass-rails completely and still saw this error

**Comment by sidazhou** [comment]
+1 on @yayayahahaha

**Comment by danpe** [comment]
+1

**Comment by shicholas** [comment]
+1 this is still an issue, updating to the master branch of ``compass-rails`` seems to be working for me.

**Comment by Frank004** [comment]
:+1:

**Comment by blmundie** [comment]
+1

**Comment by zacksiri** [comment]
+1

**Comment by tsechingho** [comment]
compass-rails 3.0 is out.
compass-rails is no longer a dependency from chosen-rails 1.5.1, please see readme.
