### ISSUE TITLE
Gem compass-rails runtime dependency

### ISSUE THREAD

**Issue by maurosbu** [tsechingho/chosen-rails#72]
Is it possible to remove the compass-rails dependency? That gem locks sprockets to version 2.12.3 and sass-rails to version 5.0.1.

Thx.

**Comment by D-system** [comment]
The scss file is just a copy/paste from Chosen. You should ask to Chosen https://github.com/harvesthq/chosen/ and/or make a pull request.

**Comment by tsechingho** [comment]
compass-rails dependency is resolved in #70.
