### ISSUE TITLE
File to import not found or unreadable: require chosen.

### ISSUE THREAD

**Issue by onlyyouandty** [tsechingho/chosen-rails#73]
Incase any one else faces this issue with Compass::Spite within the application stylesheet:

Here's my Gemfile:
gem 'chosen-rails'
gem 'sass-rails', '~> 4.0.5'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-turbolinks

And application.js
//= require jquery.turbolinks
//= require chosen-jquery

And application.css.scss
@import 'chosen';

**Comment by asecondwill** [comment]
+1

**Comment by jschroeder9000** [comment]
+1

**Comment by morshedalam** [comment]
+1
