### ISSUE TITLE
I cannot get the result as select order in controller

### ISSUE THREAD

**Issue by chadlwm** [tsechingho/chosen-rails#74]
No matter what order I select , I will get the same order in controler.

For example, I select one, then two, I get [one, two] in controller,
while I I select two, then one, I also get [one, two] in controller.

In some case, the order is important for me, how do I to do with this.

thanks in advance!

**Comment by tjschuck** [comment]
Chosen aims to be a progressive replacement for HTML select elements. Native multi-selects don't support a notion of order -- they're submitted in the order that the selected elements appear in the DOM -- therefore neither does Chosen.

See https://github.com/harvesthq/chosen/issues/1847 for more info.
