### ISSUE TITLE
Remove compass-rails dependency

### ISSUE THREAD

**Issue by maurosbu** [tsechingho/chosen-rails#79]
Hi guys,
chosen-rails is a great gem, but depends on compass-rails one.
The compass-rails gem locks sprockets to version 2.12.4 and unfortunately its maintenance is sporadic.
Is it possible to remove this dependency? Is it possible to automatically generate a scss file that does not require compass and put it in the gem?

Many thanks,
Mauro

**Comment by vad4msiu** [comment]
+1 for removal compass-rails

**Comment by asecondwill** [comment]
+1

**Comment by mlensment** [comment]
+1

**Comment by brendon** [comment]
Yes please! :)

**Comment by asiniy** [comment]
+1

**Comment by asiniy** [comment]
+1

**Comment by tirdadc** [comment]
+1, this is the only thing preventing an upgrade to Sprockets 3 for me.

**Comment by tsechingho** [comment]
Hi, all.
I will remove `compass-rails` dependency IN THESE DAYS.

**Comment by maurosbu** [comment]
@tsechingho thank you! I'm using the gem in a dozen of apps and it is the only gem preventing an upgrade to Sprockets 3.

**Comment by rhatherall** [comment]
+1

**Comment by chungphuoc** [comment]
+1

**Comment by thucnguyen** [comment]
+1

**Comment by marciotoze** [comment]
+1

**Comment by maltesa** [comment]
+1

**Comment by maurosbu** [comment]
Hope to see a new release soon :)

**Comment by maurosbu** [comment]
A new version of compass-rails has been released: sprockets no longer locked to version 2.

**Comment by knightq** [comment]
+1

**Comment by knightq** [comment]
Any hope to see this promised release soon?

**Comment by zedtux** [comment]
+1

**Comment by tsechingho** [comment]
I finally have time to do this.

compass-rails is no longer a dependency from chosen-rails 1.5.1, please see readme.

**Comment by brendon** [comment]
Thanks for this! :)

**Comment by maurosbu** [comment]
@tsechingho thank you, but it is not working unless you put compass-rails in Gemfile (as specified in README).
If I don't put compass-rails in Gemfile I get the following error:

    cannot load such file -- compass-rails (LoadError)
      /usr/local/rvm/gems/ruby-2.3.0/gems/chosen-rails-1.5.1/lib/chosen-rails.rb:17:in 'require'
      /usr/local/rvm/gems/ruby-2.3.0/gems/chosen-rails-1.5.1/lib/chosen-rails.rb:17:in '<top (required)>'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in 'require'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in 'block (2 levels) in require'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in 'each'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in 'block in require'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in 'each'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in 'require'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in 'require'
      ...

**Comment by tsechingho** [comment]
@maurosbu you are right, I forgot to remove the require line. You have v1.5.2 now.

**Comment by maurosbu** [comment]
@tsechingho thank you, it is working now!!!

**Comment by zedtux** [comment]
Thank you @tsechingho !

**Comment by justinxreese** [comment]
I feel like the references to compass should be removed from the README. Is there any reason to keep them now? They seem to just add confusion now that it is no longer a dependency.

**Comment by brendon** [comment]
@justinxreese, since this issue is closed, you should open a new issue so that it gets more visibility. Or since it's a quick change, do a pull request with the compass parts removed from the `README` and @tsechingho can go from there :)

**Comment by justinxreese** [comment]
I figured it was worth a slight mention here because I didn't know if there
was a good reason it was still in that could easily be dismissed. But I
think a new issue might be worth adding now.
