### ISSUE TITLE
Update to latest chosen (1.7)

### ISSUE THREAD

**Issue by ninjarabbi** [tsechingho/chosen-rails#93]
Hi, chosen just released a new version 2 days ago. Could you please update the gem? Thanks.

**Comment by dstull** [comment]
yes - please.  Is anyone maintaining this anymore?  I can't use rails assets due to firewalls, so I need the gem to be updated as I have access to that.

**Comment by maurosbu** [comment]
Chosen 1.8.2 is out.

**Comment by AleksandrLeontev** [comment]
Looks like need to remove this gem wrapper and replace to native bower JS library, because author forgot about gem.

**Comment by maurosbu** [comment]
Hi folks, what about https://rails-assets.org/#/components/chosen ?

**Comment by tsechingho** [comment]
sorry for lazy, I am back and just update to 1.8.2
