### ISSUE TITLE
sass-rails dependency

### ISSUE THREAD

**Issue by knightq** [tsechingho/chosen-rails#95]
Wouldn't be better to replace the `sass-rails` dependency with `sassc-rails` which is way faster than the first one?

**Comment by tsechingho** [comment]
right, I will loose the dependency.

**Comment by mileslane** [comment]
This is more urgent now.  http://sass.logdown.com/posts/7081811

**Comment by jkimmeyer** [comment]
@tsechingho Hi, any updates here? I can also provide a PR in case you are to busy.

**Comment by xinlangzi** [comment]
any update to use sassc-rails?

**Comment by florish** [comment]
@jkimmeyer Would you still be able to create a PR? I'm upgrading a Rails app right now and the Ruby Sass deadline is approaching soon, says the post-install message:

> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

If not, I'll try and see what I can do.

**Comment by JulienItard** [comment]
Is it planned to use sassc ?

**Comment by tsechingho** [comment]
Sorry for late response.
We have v1.9.0 to use sassc-rails now.
