### ISSUE TITLE
Partial string search (contains)

### ISSUE THREAD

**Issue by pbunsee** [tsechingho/chosen-rails#96]
I am trying to configure partial matching for chosen-rails like this but it has no effect. The search only matches on strings that "starts with" the search term:
```
$ ->
  # enable chosen js
  $('.chosen-select').chosen
    search_contains: true
    allow_single_deselect: true
    disable_search_threshold: 10
    no_results_text: 'No results matched'
    width: 'auto'

```

I see that search_contains has been implemented in the original chosen js library:
https://github.com/harvesthq/chosen/issues/1081

Has the above change been included in the chosen-rails gem?

**Comment by streeet25** [comment]
did you have some solution with your question?

**Comment by pbunsee** [comment]
No solution found with chosen-rails.

I switched to using select2-rails which has turned out to be awesome! - very performant, can do searches and it has features like multi-select, etc.
