### ISSUE TITLE
Unable to load chosen-sprite.png

### ISSUE THREAD

**Issue by Fredar** [tsechingho/chosen-rails#97]
Seems like last update has broken the `chosen-sprite.png` in production.

I can see in the last commit that the `image-url` was changed to `url`
https://github.com/tsechingho/chosen-rails/commit/b9ea71b10e361f4327819f55afb8252c77e1b51e#diff-be0b0e9aa033e51570b0a1a8886aef4aL4

Yet in other files it remained the same
https://github.com/tsechingho/chosen-rails/blob/master/vendor/assets/stylesheets/chosen.scss#L6

Not sure if thats the reason though.

**Comment by Fredar** [comment]
Came across this comment which explains the issue
https://stackoverflow.com/questions/9304607/sass-rails-helpers-image-url-asset-url-are-not-working-in-rails-3-2-1#comment22212758_11819234

Indeed with 1.8.2 it tries to call the file without the fingerprint.

**Comment by macfanatic** [comment]
Appears #98 was meant to resolve this, but using `1.8.3` in production causes the same error as above in this thread.

Perhaps https://github.com/tsechingho/chosen-rails/blob/master/vendor/assets/stylesheets/chosen-base.scss#L3 should be updated to use `image-url` sass function as well as the changes introduced in #98?

**Comment by macfanatic** [comment]
I was able to resolve my issue in production, still using version `1.8.3`, by defining the variables before importing the chosen CSS.

Example:

```sass
// app/assets/stylesheets/application.scss
$chosen-sprite: image-url('chosen-sprite.png');
$chosen-sprite-retina: image-url('chosen-sprite@2x.png');

@import "chosen";
```

**Comment by tsechingho** [comment]
I will fix this recently.

**Comment by jhanggi** [comment]
Any chance of getting this resolved? I have both a Rails 4.2 project and a Rails 5.2 project where this is an issue. @macfanatic's fix works great afor both, but it would be great got get this fixed in the main release. Thanks!

**Comment by donv** [comment]
I still have to apply @macfanatic 's fix with chosen-rails 1.8.7.

**Comment by donv** [comment]
(Ignore my previous comment.  I had an override in a local file)

I think this issue can be closed as fixed.

**Comment by Fredar** [comment]
Fixed with https://github.com/tsechingho/chosen-rails/pull/101/files
